### ISSUE TITLE
[style] 글로벌 스타일 셋팅

### ISSUE THREAD

**Issue by HanCheo** [woowa-techcamp-2021/store-10#10]
## 개요 
global style scss -> styled-component
## 소요 시간 

- 예상 완료 시간 : 1h
- 실제 투입 시간 : 

## 진행 사항 

- [ ] global style scss를 styled-components 형태로 변환

**Comment by Kyun2da** [comment]
이 친구 이슈 닫을게여~

**Comment by Kyun2da** [comment]
아 아직 styled로 안바꿔서 닫으면 안되겠네요.. ㅋㅋㅋ
