### ISSUE TITLE
[feat] 장바구니 삭제 확인 모달

### ISSUE THREAD

**Issue by dongqui** [woowa-techcamp-2021/store-10#116]
## 개요 
장바구니 아이템을 삭제 할 때 확인 받는 모달을 개발
## 소요 시간 

- 예상 완료 시간 : 1h
- 실제 투입 시간 : 

## 진행 사항 

- [x] 모달 개발

**Comment by Kyun2da** [comment]
찜 삭제 모달도 같은 맥락이라고 생각해서 공통으로 타이틀, 취소버튼, 확인버튼이 있는 모달 하나 만들면 좋을 것 같아요

**Comment by KangyeolLee** [comment]
제가 만들었나이다
