### ISSUE TITLE
[feat] 공지사항 페이지 작성

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/store-10#118]
## 개요 

- Footer에서 접근하는 공지사항 관련 페이지를 제작합니다.
- Collapse를 이용해서 작성하면 될 거 같으네요

> 백엔드 API 연동을 하기 귀찮은 자의 마지막 발악

## 소요 시간 

- 예상 완료 시간 : 1h
- 실제 투입 시간 : 

## 진행 사항 

- [ ] 공지사항 관련 페이지 제작
- [ ] Collapse 컴포넌트로 공지사항 출력
- [ ] 페이지네이션

**Comment by dongqui** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ
