### ISSUE TITLE
[bug] name 없는 깃헙 유저 처리

### ISSUE THREAD

**Issue by dongqui** [woowa-techcamp-2021/store-10#121]
## 개요 
깃헙 로그인시에,
깃헙 프로필에 이름을 안 써놓은 유저는 에러가 발생합니다.

## 소요 시간 

- 예상 완료 시간 : 0.5h
- 실제 투입 시간 : 

## 진행 사항 

- [x] 에러 처리

**Comment by Kyun2da** [comment]
이거 제가 회원가입 로그인 로직 구현하면서 같이 해볼게요~

**Comment by Kyun2da** [comment]
여기에 authorize할 때도 cancel누르면 QueryFailedError: Field 'user_id' doesn't have a default value 가뜨네요 같이 해결해보겠습니다.

**Comment by KangyeolLee** [comment]
이슈 덕분에 깃허브 name 을 처음으로 추가했습니다!
