### ISSUE TITLE
1팀 코드리뷰

### ISSUE THREAD

**Issue by cothis** [woowa-techcamp-2021/store-10#156]
1팀 리뷰 여기에 적어요.

**Comment by TsooranKim** [comment]
[#4](https://github.com/woowa-techcamp-2021/store-10/pull/4/files#r692680795) tsconfig.json 설정

저 이거 했어요!

**Comment by cothis** [comment]
https://github.com/woowa-techcamp-2021/store-10/pull/139#discussion_r692677866
https://github.com/woowa-techcamp-2021/store-10/pull/65#discussion_r692683134

**Comment by CurlyBat** [comment]
[리뷰(사실 리뷰 아닌듯..)](https://github.com/woowa-techcamp-2021/store-10/pull/134#pullrequestreview-734688425)

**Comment by KangyeolLee** [comment]
여러분의 성원에 힘 입어 프로젝트를 마무리 해보겠습니다 ㅎㅎ핳하
