### ISSUE TITLE
[refactor] react-query - response 관련 type 수정

### ISSUE THREAD

**Issue by dongqui** [woowa-techcamp-2021/store-10#157]
## 개요 
통일한 Response 형태에 맞게 react-query, api 타입을 수정합니다!
## 소요 시간 

- 예상 완료 시간 : 0.5h
- 실제 투입 시간 : 

## 진행 사항 

- [x] 타입 수정

**Comment by Kyun2da** [comment]
@dongqui 동진님 이거 close해도 될것같습니다! 보시면 close해주세용~

**Comment by KangyeolLee** [comment]
대신 클로즈 해버리기!
