### ISSUE TITLE
[feat] 메인페이지

### ISSUE THREAD

**Issue by HanCheo** [woowa-techcamp-2021/store-10#162]
## 개요 

1. 프로모션 작업
2. 아이템 갯수 수정 12
3. typeorm porduct item : discount 컬럼추가
-> 할인율
4. 만드는 사람이 색깔 알아서 정하기
카드 상단 색상 ( 기본색상, 베스트, 신상품, 추천 )
5. 메인에서 링크 연결할때 상품 아이디 달기
6. 할인율 랜덤으로 추가하기

## 소요 시간 

- 예상 완료 시간 : 4h
- 실제 투입 시간 : 6h

## 진행 사항 

- [x] 1. 프로모션 작업
- [x] 2. 아이템 갯수 수정 12
- [x] 3. typeorm porduct item : discount 컬럼추가
-> 할인율
- [x] 4. 만드는 사람이 색깔 알아서 정하기
카드 상단 색상 ( 기본색상, 베스트, 신상품, 추천 )
- [x] 5. 메인에서 링크 연결할때 상품 아이디 달기
- [x] 6. 할인율 랜덤으로 추가하기

**Comment by KangyeolLee** [comment]
한철님 작업중 - 카테고리별 색상만 지정되면 종료하게씁니다
