### ISSUE TITLE
[bug] 상품 줌 사용 이후 DOM이 사라지지 않는 문제

### ISSUE THREAD

**Issue by hwookim** [woowa-techcamp-2021/store-10#197]
## 개요 

![스크린샷 2021-08-23 오후 7 53 25](https://user-images.githubusercontent.com/45786387/130435780-8dacfbd7-a39d-4b36-9592-e1e179b7d4e3.png)

- 상품 줌 사용 이후 DOM이 사라지지 않아 수량 조정 버튼을 이용할 수 없는 문제

## 소요 시간 

- 예상 완료 시간 : 5m
- 실제 투입 시간 : 1m

## 진행 사항 

- [x] 상품 줌 미사용 시 DOM 삭제

**Comment by KangyeolLee** [comment]
엌 감사합니다 👍👍👍
