### ISSUE TITLE
[bug] github 로그인 시도 하면 약관동의를 안받아요.

### ISSUE THREAD

**Issue by cothis** [woowa-techcamp-2021/store-10#287]
## 개요 

약관동의 없이 그냥 가입처리가 되는것 같습니다.

## 소요 시간 

- 예상 완료 시간 : 3h
- 실제 투입 시간 : 

## 진행 사항 

- [ ] 버그 해결

**Comment by Kyun2da** [comment]
이 부분은 로직상 바뀔 부분이 많을 것 같아 해결을 안하는쪽으로 판단을 내렸습니다. 그러하여 이슈 닫습니당...
