### ISSUE TITLE
[refactor] 스토리북 리펙토링

### ISSUE THREAD

**Issue by Kyun2da** [woowa-techcamp-2021/store-10#335]
## 개요 

스토리북을 리펙토링 해보자~

## 소요 시간 

- 예상 완료 시간 : 
- 실제 투입 시간 : 

## 진행 사항 

- [ ] 스토리북 컴포넌트 고도화
- [ ] 스토리북 필요없는 것들 삭제 및 리펙토링

**Comment by HanCheo** [comment]
이슈 ! 
msw는 여전히 안되는 듯합니다.
이전에 봤던 msw, 크로매틱이 같이 잘 동작하지 않는 이슈가 근본인 듯합니다.
결국 현재 크로매틱에서 오류가 나는 스토리북(헤더, 카테고리 페이지) 
api server를 https 형태로 변경해야 합니당...;;

작업은 할 수있는데 
이 작업은 nginx 설정, 기타 설정들이 있어 추가적으로 시간이 꽤 걸릴듯 하네영..!
10시 전까지 제가 해보고 결과 알려드릴께용

**Comment by Kyun2da** [comment]
잘가 스토리북 고마웠어~
