### ISSUE TITLE
[chore] 풀 리퀘스트 리뷰어 자동 등록 설정 파일 작성

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/store-10#36]
## 개요 

- 리뷰어 자동추천 알고리즘이 너무나 빈약한 관계로 일일이 리뷰어 지정해야 하는게 넘나 번거롭습니다.
- 그러니깐 yml 파일로 만들어 관리해봅시다.

## 소요 시간 

- 예상 완료 시간 : 5m
- 실제 투입 시간 : 5m

## 진행 사항 

- [x] reviewer-lottery.yml 파일 작성

**Comment by Kyun2da** [comment]
앗 뭐야 이거 제가 방금 올린거랑 똑같은 것 같네요..? 이슈가 있는지 모르고 등록해버렸군요.. pr만 링크 달아놓고 머지되면 같이 닫도록 하겠습니다!

#38
