### ISSUE TITLE
[chore]: 프론트 테스트 코드 기본

### ISSUE THREAD

**Issue by HanCheo** [woowa-techcamp-2021/store-10#5]
## 개요 

프론트 예시용 테스트 코드 작성

## 소요 시간 

- 예상 완료 시간 : 1시간
- 실제 투입 시간 : 1시간

## 진행 사항 

- [x] 프론트 테스트 기본 코드 작성

**Comment by KangyeolLee** [comment]
커밋이 되었으므로 종료하겠습니다~
