### ISSUE TITLE
10팀 페어 코드 리뷰

### ISSUE THREAD

**Issue by ag502** [woowa-techcamp-2021/store-10#51]
## 소요 시간 

- 예상 완료 시간 : 
- 실제 투입 시간 : 

## 진행 사항 

- [ ] todo1
- [ ] todo2

**Comment by junbeomAn** [comment]
#15 
#35

**Comment by ag502** [comment]
#46
#15

많은 걸 참고하고 갑니다~~~👍

**Comment by jiho9505** [comment]
#47
#38
#43
#20

잘 배우고 갑니다 👍

**Comment by Hyoukjoo** [comment]
#45 
#38 

깔끔한 코드와 github-action을 활용한 부분이 너무 인상적입니다. 많이 배웠습니다~

**Comment by KangyeolLee** [comment]
질문 남겨주신 부분에 대해서 제가 관여한 부분은 짤막하게 답변 달아드렸습니다~~
