### ISSUE TITLE
[chore] ssr 기본 세팅 및 라우터 설정

### ISSUE THREAD

**Issue by Kyun2da** [woowa-techcamp-2021/store-10#6]
## 개요 

동진님이 짜오신 코드를 베이스로 ssr 기본 설정 및 라우터 설정

## 소요 시간 

- 예상 완료 시간 : 30m
- 실제 투입 시간 :  1h 20m

## 진행 사항 

~~[ ] ssr 기본 세팅~~
- [x] 라우터 설정

**Comment by KangyeolLee** [comment]
SSR은 본인 의사로(?) 자진 하차하였습니다.

**Comment by Kyun2da** [comment]
ssr 나중에 보자.. 한번만 봐준다 ..
