### ISSUE TITLE
[feat] 주문 현황 컴포넌트 마크업

### ISSUE THREAD

**Issue by dongqui** [woowa-techcamp-2021/store-10#99]
## 개요 
주문 현황을 보여주는 컴포넌트를 개발합니다.
<img width="821" alt="스크린샷 2021-08-17 오전 1 28 15" src="https://user-images.githubusercontent.com/21697238/129597336-8d827ae0-593e-4223-bb7c-87e2ac6b467a.png">

## 소요 시간 

- 예상 완료 시간 : 4h
- 실제 투입 시간 : 

## 진행 사항 

- [ ] 마크업

**Comment by KangyeolLee** [comment]
마크업이 아직도 안 끝났다니..!

**Comment by dongqui** [comment]
😢
